name: develop

on:
  push:
    branches:
      - 'develop'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: test-bump
        run: |
          npm install
          npm test
          node node_modules/.bin/release-it --ci --dry-run
      - name: npm-install
        run: npm install
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bokker/rss.to.telegram:develop bokker/rss.to.telegram:${{ steps.package-version.outputs.current-version}}
